### ISSUE TITLE
js1.js/printing arrays with/ without line breaks

### ISSUE THREAD

**Issue by 0iseaux** [0iseaux/hyf-javascript1#1]
The code below is part of the assignment.

```
favAnimals = ['koala', 'wombat', 'axolotl', 'alpaca', 'capybara', 'quokka']
console.log(favAnimals)
favAnimals.push('baby pig')
console.log(favAnimals)

```
returns:
```
[ 'koala', 'wombat', 'axolotl', 'alpaca', 'capybara', 'quokka' ]
[ 'koala',
  'wombat',
  'axolotl',
  'alpaca',
  'capybara',
  'quokka',
  'baby pig' ]
```

Question: Why does the 1st print give the array in 1 single line, whereas the 2nd print give a new line to each element? 
The only explicit operation that has been done to the 2nd one was the appending (pushing), and no "\n" has been used.

**Comment by ChristerNilsson** [comment]
Did you print using node.js or the browser?
I think the width of the window decides hor or ver printing. Try changing the width by dragging an edge.
You may also try to join with '\n'.

**Comment by 0iseaux** [comment]
I printed using node.js
They printed differently as shown with the same window width (I didn't adjust the window at all).
I tried adjusting the window width this time and the first print only started looking like the second one when the window got to as narrow as one element's length.

**Comment by 0iseaux** [comment]
Printing at the browser console had no such problem at all!

**Comment by ChristerNilsson** [comment]
I'm using node.js in Code:
When printing the output tries to fit in maximum number of "words" in every line.
Exactly like a normal wordprocessor.
I took two screen dumps with the same data.
```
print('##########') 
a = 'asdad asd asdsd asda dasd as asd ad asd'.split(' ')
print(a)  
print([12,23,34])
print('##########')  
```
![1](https://user-images.githubusercontent.com/3437195/58387488-532f8a00-800f-11e9-91f0-1e713c24a1f4.JPG)
![2](https://user-images.githubusercontent.com/3437195/58387489-57f43e00-800f-11e9-8e61-42483a3a36fa.JPG)

**Comment by ChristerNilsson** [comment]
If you want to be sure to have exactly one item on each line you have to use a.join('\n')

**Comment by 0iseaux** [comment]
So the issue seems to lie with node.js only.
I still don't understand why the arrays are printed differently in node.js, without the use of any '\n' or .join('\n') anywhere
![print_arrays_node](https://user-images.githubusercontent.com/49612325/58429179-4fe6dd80-80a5-11e9-82ee-c3e5fa1d25c9.png)
.

**Comment by ChristerNilsson** [comment]
It seems like there is a difference. We have to understand that node.js and the browser have lots of differences. The browser is not allowed to read and write files for security reasons. Console.log might be implemented differently between them. The disrepancy you have found is not important, as the user mainly looks at the browser only. Fullstack developers are probably the only people hurt by this anomaly.

**Comment by ChristerNilsson** [comment]
If you decide to never print branches in the tree, just the leafs, you will have full control.

**Comment by 0iseaux** [comment]
Now I see why the differences wouldn't really matter if we're just concerned with what is shown in the web browsers.
I am simply curious what caused the difference (e.g. some configurations of the terminal which dictate a line break whenever the line exceeds x characters, even if it doesn't fill the whole window width?)
By printing the leaves, not the branches, do you mean just picking which elements in the array, rather taking the whole array, to print?

**Comment by ChristerNilsson** [comment]
Instead of 
console.log([1,2,3])
you do
console.log(1,2,3)
or even
console.log('1\n2  3')
